### PR TITLE
Add Chinese language

### PR DESCRIPTION
**Pull request by guobao2333**
Although I have added Chinese to your application. some parts are hard coded.

Besides, I found some problems with the layout of your application, but it has nothing to do with the language. You may need to fix this problem.

### CODE REVIEW

**Comment by Xtr126** [comment]
Thanks for your contribution.
I extracted some of the hard coded strings from the editor interface. They can be translated now.

**Comment by guobao2333** [comment]
@Xtr126 ~~You can now merge the code.~~ Wait, there are several hard codes.

**Comment by guobao2333** [comment]
I modified the previous translation by decompiling the built installation package, and now I need to prepare the construction from scratch.

It's because I was lazy, and I still don't remember where there is hard coding, so please wait for me for a moment.

**Comment by guobao2333** [comment]
@Xtr126 There are three hard codes as shown in the figure below.

Screenshot_2024-08-01-14-18-32-42
Screenshot_2024-08-01-14-18-41-12

**Comment by Xtr126** [comment]
They are exposed dropdown menus: https://github.com/material-components/material-components-android/blob/master/docs/components/Menu.md#exposed-dropdown-menu-example 
I'm trying to find a way to translate them using string arrays.

**Comment by Xtr126** [comment]
@guobao2333 Now they can be translated: https://github.com/Xtr126/XtMapper/blob/a4a429324663b835387ec172977c6d0d4828b04a/app/src/main/res/values-zh-rCN/strings.xml#L72

**Comment by guobao2333** [comment]
Your project may not be well known, But I would still recommend using the Crowdin website to manage the localization translation work of the project.

Although there are many people in China, few people participate in the translation work. I also found a very interesting thing. As long as the translation channels are opened for most applications, almost all Chinese will be translated😂.

Well, I won't flatter myself. You can really merge projects now.

**Comment by Xtr126** [comment]
> Your project may not be well known, But I would still recommend using the Crowdin website to manage the localization translation work of the project.
> 
> Although there are many people in China, few people participate in the translation work. I also found a very interesting thing. As long as the translation channels are opened for most applications, almost all Chinese will be translated😂.
> 
> Well, I won't flatter myself. You can really merge projects now.

I agree with you, translations should be made easier. I'll look into setting up crowdin, thanks for the suggestion. Initially I was focusing on the functionality as it took a long while to get it to a usable state.

**Comment by Xtr126** [comment]
Anyone who wants to test the changes can do so by downloading the artifact from https://github.com/Xtr126/XtMapper/actions/runs/10199678072

**Pull request merged**
