### PR TITLE
Added Arabic

### PR DESCRIPTION
**Pull request by muhammadbahaa2001**

### CODE REVIEW

**Comment by Xtr126** [comment]
Thanks for your contribution.

**Comment by Xtr126** [comment]
@muhammadbahaa2001  Can you update the translations as time allows? We are nearing next release and it would be nice to have the translations complete. Some new strings were added  https://github.com/xtr126/XtMapper/blob/dev/app/src/main/res/values-ar/strings.xml

**Comment by muhammadbahaa2001** [comment]
> @muhammadbahaa2001  Can you update the translations as time allows? We are nearing next release and it would be nice to have the translations complete. Some new strings were added  https://github.com/xtr126/XtMapper/blob/dev/app/src/main/res/values-ar/strings.xml

I'm going to update it within 2 days.

**Comment by muhammadbahaa2001** [comment]
Update:

I have updated the Arabic translation on Crowdin.
@Xtr126

**Comment by Xtr126** [comment]
> Update:
> 
> I have updated the Arabic translation on Crowdin. @Xtr126

Thank you. I merged them in #136

**Pull request merged**
